### ISSUE TITLE
Error occur when running Most Discriminating Terms

### ISSUE THREAD

**Issue by fredrik1984** [inidun/text_analytics#9]
I could not run the notebook Most Discriminating Terms. I get the following message:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c82c6439600c> in <module>
     11 from penelope.notebook.mdw import create_mdw_gui
     12 
---> 13 import __paths__
     14 
     15 view_display, view_gui = Output(), Output()

ModuleNotFoundError: No module named '__paths__'

**Comment by roger-mahler** [comment]
The file is missing in the notebook folder `most_descriminating_terms`. A quick-fix is to copy the file `__paths__.py` from folder `pos_statistics.py` to folder `most_descriminating_terms`:


![Capture](https://user-images.githubusercontent.com/17061116/105839798-4af0d480-5fd2-11eb-8923-f780057da1df.PNG)

**Comment by roger-mahler** [comment]
Fixed in code, and will be included in next release.

**Comment by fredrik1984** [comment]
Hm, I can't see that such a file exist in folder pos_statistics.py...
![Uploading Skärmavbild 2021-01-26 kl. 12.36.34.png…]()

**Comment by roger-mahler** [comment]
Hmmm...then `pos_statistics` is broken as well? The file also exists in ´word_trends` and `co_occurrence` folders. Try copying the file from any of those folders instead.

**Comment by fredrik1984** [comment]
I fixed it!
